package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

func initCmd(args []string) {
	fs := newFlagSet("init")
	outputPath := fs.StringP("output", "o", "", "write config to file (default: stdout)")
	minimal := fs.Bool("minimal", false, "generate minimal config template without interaction")

	if err := fs.Parse(args); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	var cfg string
	if *minimal {
		cfg = minimalConfigTemplate()
	} else {
		cfg = interactiveWizard()
	}

	if *outputPath != "" {
		if err := os.WriteFile(*outputPath, []byte(cfg), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "write config failed: %v\n", err)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "Config written to %s\n", *outputPath)
		fmt.Fprintf(os.Stderr, "Next: acp2larkbot test -c %s\n", *outputPath)
	} else {
		fmt.Print(cfg)
	}
}

func interactiveWizard() string {
	scanner := bufio.NewScanner(os.Stdin)

	appID := prompt(scanner, "Lark App ID", "")
	appSecret := prompt(scanner, "Lark App Secret", "")
	domain := prompt(scanner, "Lark domain (lark/feishu)", "lark")
	backendType := prompt(scanner, "ACP backend type (cmd/network)", "cmd")

	var acpSection string
	switch backendType {
	case "cmd":
		command := prompt(scanner, "ACP command (absolute path)", "/path/to/acp-server")
		cwd := prompt(scanner, "ACP working directory", "/path/to/workspace")
		acpSection = fmt.Sprintf(`acp:
  default_agent: local
  agents:
    local:
      type: cmd
      command: %s
      cwd: %s
      timeouts:
        start: 30s
        request: 10m
        idle: 30m`, command, cwd)
	case "network":
		url := prompt(scanner, "ACP websocket URL (wss://...)", "wss://example.com/acp")
		token := prompt(scanner, "ACP auth token (optional)", "")
		authSection := ""
		if token != "" {
			authSection = fmt.Sprintf(`
      auth:
        type: bearer
        token: %s`, token)
		}
		acpSection = fmt.Sprintf(`acp:
  default_agent: remote
  agents:
    remote:
      type: network
      protocol:
        transport: websocket
        binding: acp.websocket
        max_inflight: 1
      url: %s%s
      endpoint_allowlist:
        - %s
      tls:
        insecure_skip_verify: false
      heartbeat:
        type: websocket_ping_pong
        interval: 30s
        timeout: 10s
      request:
        require_request_id: true
        idempotency_ttl: 24h
      timeouts:
        connect: 10s
        request: 10m`, url, authSection, url)
	}

	chatID := prompt(scanner, "Chat ID to enable (oc_xxx, or skip)", "")
	chatsSection := "chats: []"
	if chatID != "" {
		chatsSection = fmt.Sprintf(`chats:
  - id: %s
    agent: local
    session:
      strategy: auto_create
      scope: sender
      prefix: lark
      ttl: 168h
      idle_timeout: 24h`, chatID)
	}

	return fmt.Sprintf(`# acp2larkbot config generated by 'acp2larkbot init'

log:
  level: info

lark:
  app_id: %s
  app_secret: %s
  domain: %s
  connection_mode: websocket
  ignore_self_messages: true
  ignore:
    sender_types: [bot]
    self_app_id: %s
    message_id_ttl: 24h
    max_message_ids: 10000
  trigger:
    message_types: [text]
    ignore_update_events: true
    ignore_card_events: true
    require_mention_in_group: false
  streaming:
    enabled: true
    mode: card_streaming
    update_interval: 1s
    min_update_chars: 16
    max_update_chars: 8000
    max_updates_per_message: 60
    max_stream_duration: 10m
    max_final_chars: 20000
    fallback: append_messages
    fallback_max_messages: 3
    truncate_notice: "\n\n[truncated]"

authz:
  access:
    default: deny

unknown_chat:
  behavior: reply_error
  include_chat_id: true
  rate_limit_interval: 10m

dedupe:
  enabled: true
  ttl: 24h

state:
  type: bolt
  path: ./state/acp2larkbot.db

commands:
  enabled: true
  prefix: /
  rules:
    cancel:
      roles: [user, admin]
      only_request_owner_or_admin: true
    status:
      roles: [user, admin]
      redact: true
    reset:
      roles: [admin]
      require_confirm: true
      confirm_text: RESET

%s

%s
`, appID, appSecret, domain, appID, acpSection, chatsSection)
}

func minimalConfigTemplate() string {
	return `# acp2larkbot config - fill in the values below
# Validate: acp2larkbot test -c config.yaml
# Run:      acp2larkbot run -c config.yaml

log:
  level: info

lark:
  app_id: YOUR_APP_ID
  app_secret: YOUR_APP_SECRET
  domain: lark
  connection_mode: websocket
  ignore_self_messages: true
  ignore:
    sender_types: [bot]
    self_app_id: YOUR_APP_ID
    message_id_ttl: 24h
    max_message_ids: 10000
  trigger:
    message_types: [text]
    ignore_update_events: true
    ignore_card_events: true
  streaming:
    enabled: true
    mode: card_streaming
    update_interval: 1s
    min_update_chars: 16
    max_update_chars: 8000
    max_updates_per_message: 60
    max_stream_duration: 10m
    max_final_chars: 20000
    fallback: append_messages
    fallback_max_messages: 3
    truncate_notice: "\n\n[truncated]"

authz:
  access:
    default: deny
    users:
      - id: YOUR_USER_OPEN_ID
        role: user

unknown_chat:
  behavior: reply_error
  message: This chat is not enabled for acp2larkbot.
  include_chat_id: true
  rate_limit_interval: 10m

dedupe:
  enabled: true
  ttl: 24h

state:
  type: bolt
  path: ./state/acp2larkbot.db

commands:
  enabled: true
  prefix: /
  rules:
    cancel:
      roles: [user, admin]
      only_request_owner_or_admin: true
    status:
      roles: [user, admin]
      redact: true
    reset:
      roles: [admin]
      require_confirm: true
      confirm_text: RESET

acp:
  default_agent: local
  agents:
    local:
      type: cmd
      command: /path/to/your-acp-server
      cwd: /path/to/workspace
      timeouts:
        start: 30s
        request: 10m
        idle: 30m

chats:
  - id: YOUR_CHAT_ID
    agent: local
    session:
      strategy: auto_create
      scope: sender
      prefix: lark
      ttl: 168h
      idle_timeout: 24h
`
}

func prompt(scanner *bufio.Scanner, label, defaultVal string) string {
	if defaultVal != "" {
		fmt.Fprintf(os.Stderr, "? %s [%s]: ", label, defaultVal)
	} else {
		fmt.Fprintf(os.Stderr, "? %s: ", label)
	}
	if !scanner.Scan() {
		return defaultVal
	}
	input := strings.TrimSpace(scanner.Text())
	if input == "" {
		return defaultVal
	}
	return input
}
